name: Release Build

on:
  push:
    tags:
      - "v*" # Trigger on version tags (e.g. v0.1.0)

jobs:
  build:
    name: Build and Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: Linux
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            name: macOS
            target: x86_64-apple-darwin
          - os: windows-latest
            name: Windows
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build Release Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package Binary
        shell: bash
        run: |
          mkdir -p release
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/ai-commit.exe release/
          else
            cp target/${{ matrix.target }}/release/ai-commit release/
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ai-commit-${{ matrix.name }}
          path: release/
          if-no-files-found: error
